import type { DashboardSocial } from '@/types/dashboard-social'

const EARNED = '2026-09-18T09:00:00.000Z'

export const mockDashboardSocial: DashboardSocial = {
  profile: null,
  generatedAt: '2026-10-09T10:00:00.000Z',
  operator: {
    name: 'Rohit',
    xp: 4120,
    level: 3,
    levelStartXp: 3000,
    nextLevelXp: 6000,
    streakDays: 12,
    bestStreak: 21,
    activeDays: [true, true, true, true, true, true, false],
  },
  agents: [
    {
      id: 'hermes-switch',
      initials: 'HS',
      sessions: 993,
      tokensWeek: 4_200_000,
      tasksWeek: 17,
      runsWeek: 41,
      working: true,
      topTools: ['terminal', 'herdr', 'jev_gate', 'read_file', 'git'],
    },
    {
      id: 'neo',
      initials: 'NE',
      sessions: 311,
      tokensWeek: 1_100_000,
      tasksWeek: 21,
      runsWeek: 6,
      working: true,
      topTools: ['terminal', 'pytest', 'ruff', 'sqlite'],
    },
    {
      id: 'morpheus',
      initials: 'MO',
      sessions: 120,
      tokensWeek: 86_000,
      tasksWeek: 2,
      runsWeek: 58,
      working: false,
      topTools: ['web_search', 'summarise'],
    },
    {
      id: 'trinity',
      initials: 'TR',
      sessions: 4,
      tokensWeek: 12_000,
      tasksWeek: 0,
      runsWeek: 0,
      working: false,
      topTools: ['chat'],
    },
    {
      id: 'bakeoff-ts',
      initials: 'BT',
      sessions: 2,
      tokensWeek: 3_000,
      tasksWeek: 0,
      runsWeek: 1,
      working: false,
      topTools: ['chat'],
    },
  ],
  hotTopics: [
    { label: 'dashboard revamp', href: '/chat/dashboard-revamp' },
    { label: 'matrixkoder lanes', href: '/chat/matrixkoder-lanes' },
    { label: 'workflow approvals', href: '/workflows' },
    { label: 'gateway timeouts', href: '/chat/gateway-timeouts' },
    { label: 'release v2.13', href: '/chat/release-v2-13' },
  ],
  counts: {
    chats: 1430,
    needsYou: 3,
    workflows: 106,
    cron: 8,
    tasks: 42,
    memory: 131,
    selfImprove: 11,
    gatewayOk: true,
  },
  needsYou: [
    {
      kind: 'approval',
      runId: 'run_8f2a',
      nodeRunId: 'node_8f2a_4',
      workflow: 'release-train',
      version: 'v3',
      pausedAt: '2026-10-09T08:40:00.000Z',
      progress: '4 of 6 steps',
      next: 'Publish GitHub release',
      agent: 'hermes-switch',
      at: '2026-10-09T08:40:00.000Z',
    },
    {
      kind: 'cron-failing',
      jobId: 'cron_31',
      name: 'nightly-digest',
      failures: 3,
      lastError: 'gateway timeout after 30s',
      agent: 'morpheus',
      at: '2026-10-09T03:00:00.000Z',
    },
    {
      kind: 'task-review',
      taskId: 'task_204',
      title: 'Review agents tab sidebar list',
      board: 'switchui',
      agent: 'neo',
      at: '2026-10-09T07:15:00.000Z',
    },
  ],
  recent: [
    {
      at: '2026-10-09T09:50:00.000Z',
      kind: 'chat',
      title: 'Plan the dashboard revamp',
      sub: '14 messages',
      who: 'hermes-switch',
      href: '/chat/dashboard-revamp',
    },
    {
      at: '2026-10-09T09:20:00.000Z',
      kind: 'workflow',
      title: 'release-train finished step 4',
      sub: 'waiting for approval',
      who: 'hermes-switch',
      href: '/workflows',
    },
    {
      at: '2026-10-09T08:05:00.000Z',
      kind: 'cron',
      title: 'nightly-digest failed',
      sub: 'gateway timeout after 30s',
      who: 'morpheus',
      href: '/cron',
    },
    {
      at: '2026-10-08T21:30:00.000Z',
      kind: 'task',
      title: 'Agents tab merged',
      sub: 'switchui board',
      who: 'neo',
      href: '/tasks',
    },
    {
      at: '2026-10-08T18:00:00.000Z',
      kind: 'badge',
      title: 'Badge earned: Conductor',
      sub: '50 workflow runs',
      who: 'hermes-switch',
      href: '/dashboard',
    },
  ],
  badges: [
    {
      id: 'first-chat',
      name: 'First chat',
      how: 'day one',
      have: 1,
      need: 1,
      earnedAt: EARNED,
    },
    {
      id: 'streak-7',
      name: 'Streak 7',
      how: '7 days in a row',
      have: 12,
      need: 7,
      earnedAt: EARNED,
    },
    {
      id: 'conductor',
      name: 'Conductor',
      how: '50 workflow runs',
      have: 106,
      need: 50,
      earnedAt: EARNED,
    },
    {
      id: 'gatekeeper',
      name: 'Gatekeeper',
      how: '10 approvals',
      have: 14,
      need: 10,
      earnedAt: EARNED,
    },
    {
      id: 'memory-keeper',
      name: 'Memory keeper',
      how: '100 facts saved',
      have: 131,
      need: 100,
      earnedAt: EARNED,
    },
    {
      id: 'fleet',
      name: 'Fleet',
      how: '5 agent profiles',
      have: 5,
      need: 5,
      earnedAt: EARNED,
    },
    {
      id: 'shipper',
      name: 'Shipper',
      how: '10 releases',
      have: 23,
      need: 10,
      earnedAt: EARNED,
    },
    {
      id: 'self-made',
      name: 'Self-made',
      how: '10 self-improve wins',
      have: 11,
      need: 10,
      earnedAt: EARNED,
    },
    {
      id: 'night-owl',
      name: 'Night owl',
      how: '10 sessions after midnight',
      have: 7,
      need: 10,
      earnedAt: null,
    },
    {
      id: 'token-whale',
      name: 'Token whale',
      how: '5M tokens in one week',
      have: 4_200_000,
      need: 5_000_000,
      earnedAt: null,
    },
    {
      id: 'maestro',
      name: 'Maestro',
      how: '200 workflow runs',
      have: 106,
      need: 200,
      earnedAt: null,
    },
    {
      id: 'streak-30',
      name: 'Streak 30',
      how: '30 days in a row',
      have: 12,
      need: 30,
      earnedAt: null,
    },
  ],
}

export const mockDashboardSocialEmpty: DashboardSocial = {
  profile: null,
  generatedAt: '2026-10-09T10:00:00.000Z',
  operator: null,
  agents: null,
  hotTopics: null,
  counts: null,
  needsYou: null,
  recent: null,
  badges: null,
}
